- name: Create EC2 key pair
  ec2_key:
    name: "{{ key_pair_name }}"
    region: "{{ region }}"
  register: _ec2_key

- name: Save EC2 key pair (if created)
  local_action: copy content="{{ _ec2_key.key.private_key }}" dest="~/.ssh/{{ _ec2_key.key.name }}" mode=0600
  when: _ec2_key.changed